# Invariant assignments common to all roles

# Default to local python 3 executable path
ansible_python_interpreter: "/usr/local/bin/python"

# Tag keys for all AWS resources
tag_prefix: "ngnix-lb-example"

# Resource nomenclature
stage_access_name: "{{tag_prefix}}-{{stage}}"
iam_role: "{{stage_access_name}}"

# AMI used for server instances both golang and nginx by region
# Adopting Amazon Linux as suitable basis: Amazon Linux AMI 2017.09.1 (HVM)
image_to_launch:
  eu-west-1: "ami-1a962263"
  eu-west-2: "ami-e7d6c983"
  eu-central-1: "ami-bf2ba8d0"
  us-west-1: "ami-55ef662f"
  # etc

# Public DNS
public_dns_root_domain: "ngnix-lb-example.consecutive-operations.co.uk"

# Ports invariant across all Vpcs for the internal listening port of nginx
port_nginx: 8080

