# Invariant assignments common to all roles

# Default to local python 3 executable path
ansible_python_interpreter: "/usr/local/bin/python"

# Tag keys for all AWS resources
tag_prefix: "ngnix-lb-example"

# Resource nomenclature
stage_access_name: "{{tag_prefix}}-{{stage}}"
iam_role: "{{stage_access_name}}"

# AMI used for server instances both golang and nginx by region
# Adopting Amazon Linux as suitable basis: CentOS 7 (x86_64) - with Updates HVM Dec 2017
image_to_launch:
  eu-west-1: "ami-5f76b626"
  eu-west-2: "ami-951201f1"
  eu-central-1: "ami-2540f74a"
  us-west-1: "ami-db48ada1"
  # etc

# Public DNS
public_dns_root_domain: "ngnix-lb-example.consecutive-operations.co.uk"

# Ports invariant across all Vpcs for the internal listening port of nginx
port_nginx: 8080

