- name: destroy complete VPC stack for store
  hosts: local
  vars:
      stack_state: absent
  roles:
    - { role: webloadbalancer }
    - { role: appinstancegroup }
    - { role: security }
    - { role: buckets }
    - { role: network }



