- name: launch app instance group for {{stage_access_name}} 
  cloudformation:
    profile: "{{aws_account_profile}}"
    stack_name: "{{stage_access_name}}-webloadbalancer"
    state: "present"
    region: "{{aws_region}}"
    disable_rollback: true
    template: "./roles/webloadbalancer/templates/webloadbalancer.template"
    template_parameters:
      AmazonImageId: "{{image_to_launch[aws_region]}}"
      PublicSubnets: "{{network_public_subnets}}"
      InstanceType: "t2.micro"
      VPC: "{{network_vpc}}"
      IngressSecurityCIDRRange: "{{network_cidr_for_vpc}}"   # TODO - Lock down tighter to eligible SGs
      Stage: "{{stage}}"
  register: webloadbalancer_results